### PR TITLE
fix: external link ignore mailto: & javascript:

### LINKED ISSUE #3796: hexo 4.0.0 會給 a 標簽 添加 target="_blank"
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help  to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Node.js is higher than 6.9

## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version**

```
```

**Your site `_config.yml`** (Optional)

```
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

hexo 4.0.0 會給 一些a 標簽 添加 target="_blank" 
而原本a 標簽是默認本頁打開的，導致打開a標簽會跳出一個頁面 about:blank#blocked

具體這個 hexo - douban的插件 生成的頁面
別添加 target="_blank" 后，導致點擊上一頁/下一頁/進入這個頁面 都會跳出一個about:blank#blocked 空頁面

我退回 3.9.0 后 沒發現問題。。可以斷定是hexo 4.0.0的問題

### PR DESCRIPTION
**Pull request by SukkaW**
Close #3796

## What does it do?

Fix https://github.com/hexojs/hexo/issues/3796#issuecomment-546692793

## How to test

```sh
git clone -b external-link-exclude https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

## Pull request tasks

- [x] Add test cases for the changes.
- [x] Passed the CI test.

### CODE REVIEW

File: lib/plugins/filter/after_post_render/external_link.js [hunk 1]
```diff
@@ -37,7 +37,7 @@ function externalLinkFilter(data) {
     config.external_link.field !== 'post') return;
 
   data.content = data.content.replace(/<a.*?(href=['"](.*?)['"]).*?>/gi, (str, hrefStr, href) => {
-    if (/target=/gi.test(str) || !isExternal(href, config)) return str;
+    if (/target=/gi.test(str) || href.startsWith('mailto:') || href.startsWith('javascript:') || !isExternal(href, config)) return str;
```
Comment (curbengh) [inline lib/plugins/filter/after_post_render/external_link.js]: there are countless of types (`data:`, `vbscript:` and so on), can test whether it's a link protocol (http/ftp) or not by testing whether `URL(href).origin` is null. See [`encodeURL()`](https://github.com/hexojs/hexo-util/blob/635161b3a732d3208b85269b7624e57a9816ed24/lib/encode_url.js#L24).

Comment (SukkaW) [reply lib/plugins/filter/after_post_render/external_link.js]: OK, I will change to that.

File: lib/plugins/filter/after_post_render/external_link.js [hunk 2]
```diff
@@ -1,15 +1,23 @@
...
   const exclude = Array.isArray(config.external_link.exclude) ? config.external_link.exclude :
     [config.external_link.exclude];
-  const data = parse(url);
+  const data = urlObj(url);
   const host = data.hostname;
-  const sitehost = parse(config.url).hostname || config.url;
+  const sitehost = urlObj(config.url).hostname || config.url;
 
-  if (!data.protocol || !sitehost) return false;
+  if (!data.protocol || !sitehost || !data.origin) return false;
```
Comment (curbengh) [inline lib/plugins/filter/after_post_render/external_link.js]: when there is no data.origin, it returns a string value of `'null'`, not null type.

`!data.protocol` should be removed, because it's not null even in `javascript:foobar`.

``` js
const url = new URL('javascript:foobar')
console.log(url.protocol)
// 'javascript:'
```

Comment (curbengh) [reply lib/plugins/filter/after_post_render/external_link.js]: `data` variable will be string type if `url` is internal link.

you need to check the type of `data` first, otherwise `data.origin` will cause error if internal link.

``` js
if (!sitehost || typeof data === 'string') return false;
if (data.origin === 'null') return false;
```

File: test/scripts/filters/external_link.js [hunk 3]
```diff
@@ -208,23 +208,27 @@ describe('External link - post', () => {
       '# External link test',
       '1. External link',
       '<a href="https://hexo.io/">Hexo</a>',
-      '2. External link with "rel" Attribute',
+      '2. Link with hash (#), mailto: , javascript: shouldn\'t be processed',
+      '<a href="#top">Hexo</a>',
```
Comment (curbengh) [inline test/scripts/filters/external_link.js]: :+1:

**Comment by SukkaW** [comment]
I might implement `is_external_link()` helper in another PR, so that `isExternal()` can be used acrossed both filters.
