### PR TITLE
fix(post): swig tag inside post

### LINKED ISSUE #3259: {{ should not be rendered in a post
## Environment Info

Node version(`node -v`): v10.9.0

Hexo and Plugin version(`npm ls --depth 0`): 

```
├── hexo@3.7.1
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.2
├── hexo-generator-json-content@3.0.1
├── hexo-generator-tag@0.2.0
├── hexo-i18n@0.2.1
├── hexo-multiauthor@0.0.1
├── hexo-pagination@0.1.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-markdown-it@3.4.1
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.3.3
├── hexo-sliding-spoiler@1.1.6
├── hexo-tag-asciinema@0.0.1
└── hexo-tag-bootstrap@0.1.2
```

## For BUG

I think I get this error message an hundred times:

```javascript
Template render error: (unknown path) [Line 69, Column 34]
  unexpected token: }}
    at Object._prettifyError (/home/shark/Dev/hexo_rawsec/node_modules/nunjucks/src/lib.js:36:11)
    at Template.render (/home/shark/Dev/hexo_rawsec/node_modules/nunjucks/src/environment.js:524:21)
    at Environment.renderString (/home/shark/Dev/hexo_rawsec/node_modules/nunjucks/src/environment.js:362:17)
    at Promise (/home/shark/Dev/hexo_rawsec/node_modules/hexo/lib/extend/tag.js:66:9)
    at Promise._execute (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/home/shark/Dev/hexo_rawsec/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/home/shark/Dev/hexo_rawsec/node_modules/hexo/lib/hexo/post.js:230:16)
    at Promise.then.then.result (/home/shark/Dev/hexo_rawsec/node_modules/hexo/lib/hexo/render.js:65:19)
    at tryCatcher (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/shark/Dev/hexo_rawsec/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
```

Because I used `{{` or `}}` in my markdown files. Because I'm writing technical stuff about templating languages for example.
This is making the EJS template engine crash.

But instead of trying to compute all files blindly, Hexo should make the EJS engine aware of the markdown context.

I mean if there is `}}` or `%}` ok try to do something with it but if the same pattern is inside markdown inline or fenced block just ignore it, it's not for you silly EJS engine.

Same for other languages (other than markdown) and stuff inside a comment.

The EJS engine is blind, make him some eyes please.

Sometimes even using the `{% raw %}` tag I can't write the code I want to.

An additional mechanism can be to make a switch to turn off EJS parsing 1) globally in _config.yml and 2) locally inside the file frontammeter. 

Not a marked problem. Marked render that as expected.

Related issue: #2030

### PR DESCRIPTION
**Pull request by SukkaW**
## What does it do?

The PR fixes #3259, #3346 & https://github.com/hexojs/hexo/issues/3346#issuecomment-595497849

## How to test

```sh
git clone -b test-post-render-swig https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

## Pull request tasks

- [x] Add test cases for the changes.
- [x] Passed the CI test.

### CODE REVIEW

**Comment by SukkaW** [comment]
The fixes for #3543 is not included.

Maybe I will open an another PR.

File: test/scripts/hexo/post.js [hunk 1]
```diff
@@ -669,13 +669,13 @@ describe('Post', () => {
   });
 
   it('render() - recover escaped nunjucks blocks which is html escaped', () => {
-    const content = '`{% raw %}{{ test }}{% endraw %}`';
+    const content = '`{% raw %}{{ test }}{% endraw %}`, {%raw%}{{ test }}{%endraw%}';
```
Comment (SukkaW) [inline test/scripts/hexo/post.js:672]: The alter of the test case here is to test my newly added `rSwigRawFullBlock`

File: test/scripts/hexo/post.js [hunk 2]
```diff
@@ -1004,4 +1004,29 @@ describe('Post', () => {
...
+  // https://github.com/hexojs/hexo/issues/3259
+  it('render() - "{{" & "}}" inside inline code', async () => {
+    const content = 'In Go\'s templates, blocks look like this: `{{block "template name" .}} (content) {{end}}`.';
+
+    const data = await post.render(null, {
+      content,
+      engine: 'markdown'
+    });
+
+    data.content.trim().should.eql('<p>In Go’s templates, blocks look like this: <code>&amp;#123;&amp;#123;block &quot;template name&quot; .&amp;#125;&amp;#125; (content) &amp;#123;&amp;#123;end&amp;#125;&amp;#125;</code>.</p>');
```
Comment (stevenjoezhang) [inline test/scripts/hexo/post.js:1018]: It seems that `&amp;#123;` is escaped twice and it's displayed as `&#123;` instead of `{` in the browser. Is this expected?

Comment (SukkaW) [reply test/scripts/hexo/post.js:1018]: I will update the test case using `escapeHTML` to make it clearer.

Comment (SukkaW) [reply test/scripts/hexo/post.js:1018]: @stevenjoezhang 

The `marked.js` will escape code by default, thus caused double escape.
